name: awi-project-tracker
services:
- name: web
  source_dir: /
  github:
    repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
    branch: main
  run_command: gunicorn app:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /
  envs:
  - key: FLASK_ENV
    value: production
  - key: SECRET_KEY
    value: your-secret-key-here
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: OPENAI_API_KEY
    value: your-openai-api-key
  - key: SENDGRID_API_KEY
    value: your-sendgrid-api-key
  - key: EMAIL_FROM
    value: your-email@example.com
  - key: MONGODB_URI
    value: your-mongodb-connection-string
  - key: PYTHON_ENV
    value: production

databases:
- name: db
  engine: PG
  version: "13"
  production: false
  cluster_name: awi-project-tracker-db 