"""add image_description column

Revision ID: 61a6e12a1e10
Revises: d8c96db3a5f4
Create Date: 2025-06-05 12:44:56.937699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a6e12a1e10'
down_revision = 'd8c96db3a5f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('image_description', sa.Text(), nullable=True))
    op.add_column('sample_trash', sa.Column('image_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_trash', 'image_description')
    op.drop_column('sample', 'image_description')
    # ### end Alembic commands ###
