"""Add sample_image column

Revision ID: d8c96db3a5f4
Revises: 
Create Date: 2025-06-04 11:47:25.781854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8c96db3a5f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_logs')
    op.add_column('sample', sa.Column('sample_image', sa.String(length=500), nullable=True))
    op.add_column('sample_trash', sa.Column('sample_image', sa.String(length=500), nullable=True))
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('sample_trash', 'sample_image')
    op.drop_column('sample', 'sample_image')
    op.create_table('query_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_input', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('generated_sql', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('execution_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('row_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='query_logs_pkey')
    )
    # ### end Alembic commands ###
